### ISSUE TITLE
Metrics breaking change: tentant id no longer part of URL

### ISSUE THREAD

**Issue by vnugent** [Hawkular-QE/hawkular-java-client#14]
https://issues.jboss.org/browse/HWKMETRICS-68

https://github.com/hawkular/hawkular-metrics/pull/202

**Comment by garethahealy** [comment]
@vnugent : can this issue be closed?

**Comment by jkandasa** [comment]
@vnugent 
This is a too old issue. Current approach handles tenant id in a different way. We can close this issue.
