### ISSUE TITLE
Refactor successful status code into composite Response object

### ISSUE THREAD

**Issue by vnugent** [Hawkular-QE/hawkular-java-client#20]
Recent PRs introduce a boolean status to some APIs.  

```
boolean createTenant(Tenant tentant); // returns true if successful, false otherwise
Tenant getTenant(String id);  // how to determine status, non-null, runtime-exception?
```

I suggest for consistency sake we can either 
1. throw an exception (runtime or checked) and expect user to handle it
2.  introduce a Response object.  Something like

```
interface Response <T> {
  bolean getStatus();
  HTTPResponse getHTTPResponse(); 
  T Response.getData();
}
```

@jkandasa

**Comment by jkandasa** [comment]
@vnugent 
Is this fine to close this ticket?

https://github.com/Hawkular-QE/hawkular-java-client/blob/master/src/main/java/org/hawkular/client/ClientResponse.java

**Comment by vnugent** [comment]
I have a work-in-progress PR to handle ClientResponse in metrics portion.  Let me get it in the next few days.
