### ISSUE TITLE
Travis-ci tests fail due to livingontheedge in FAILED state

### ISSUE THREAD

**Issue by garethahealy** [Hawkular-QE/hawkular-java-client#41]
I believe this is due to:

`http://livingontheedge.hawkular.org/hawkular/metrics/status/`

Returning:

```
{
  "MetricsService": "FAILED",
  "Implementation-Version": "0.19.0.Final",
  "Built-From-Git-SHA1": "c970612a4c8b61d109fbdf65b75508c28102055e"
}
```

Which causes for getTenant (http://livingontheedge.hawkular.org/hawkular/metrics/tenants/):

`https://github.com/hawkular/hawkular-client-java/blob/master/src/test/java/org/hawkular/client/test/metrics/TenantTest.java#L41`

To fail with:

```
{
  "errorMsg": "WELD-000052: Cannot return null from a non-dependent producer method: Producer for Producer Method [MetricsService] with qualifiers [@Any @Default] declared as [[BackedAnnotatedMethod] @Produces @ApplicationScoped public org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle.getMetricsService()] declared on Managed Bean [class org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle] with qualifiers [@Any @Default]\n\tat org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle.getMetricsService(MetricsServiceLifecycle.java:0)\n  StackTrace:"
}
```

**Comment by garethahealy** [comment]
Related to: https://issues.jboss.org/browse/HAWKULAR-1120

**Comment by garethahealy** [comment]
@pilhuhn or @vnugent : when you get a chance, can you maybe have a look at this?

**Comment by pilhuhn** [comment]
This should be an issue of the past with #43 as we now fire up hawkular in Docker to test against, so each time you get a fresh clean install.

**Comment by jotak** [comment]
Travis tests now use serverless docker containers instead of livingontheedge server, so they pass now
